#%RAML 1.0
title: product-api
baseUri: http://localhost:8081/products
/products:
  get:
    description: to get products
    responses:
      200:
        body:
          application/json:
            example:
              {
                "productID":"1354686",
                "productName":"Mulesoft Course",
                "productProvider":"Udemy",
                "productDescription":"Complete Mulesoft Developer Course"
              }
            
          
